  
language: go

env:
  - AWS_DEFAULT_REGION=us-east-1
os:
  - linux

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - mkdir /tmp/helm
  - wget https://get.helm.sh/helm-v3.3.4-linux-amd64.tar.gz -O /tmp/helm/helm.tar.gz
  - tar xzvf /tmp/helm/helm.tar.gz -C /tmp/helm
  - mv /tmp/helm/linux-amd64/helm /tmp/helm/helm
  - chmod u+x /tmp/helm/helm

script:
  - chmod +x build-chart-autoscaler.sh && ./build-chart-autoscaler.sh  
  - chmod +x build-chart-heapster.sh && ./build-chart-heapster.sh
  - chmod +x build-chart-ingress.sh && ./build-chart-ingress.sh
  - chmod +x build-chart-kube2iam.sh && ./build-chart-kube2iam.sh
  - chmod +x build-chart-kuberos.sh && ./build-chart-kuberos.sh
  
deploy:
  
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    bucket: "helm-repo.sphera.tools"
    skip_cleanup: true
    region: "${AWS_DEFAULT_REGION}"
    local_dir: build-autoscaler
    upload-dir: cluster-autoscaler
    on:
      branch: main
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    bucket: "helm-repo.sphera.tools"
    skip_cleanup: true
    region: "${AWS_DEFAULT_REGION}"
    local_dir: build-heapster
    upload-dir: heapster
    on:
      branch: main
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    bucket: "helm-repo.sphera.tools"
    skip_cleanup: true
    region: "${AWS_DEFAULT_REGION}"
    local_dir: build-ingress
    upload-dir: aws-alb-ingress-controller
    on:
      branch: main
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    bucket: "helm-repo.sphera.tools"
    skip_cleanup: true
    region: "${AWS_DEFAULT_REGION}"
    local_dir: build-kube2iam
    upload-dir: kube2iam
    on:
      branch: main
      branch: main
  - provider: s3
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    bucket: "helm-repo.sphera.tools"
    skip_cleanup: true
    region: "${AWS_DEFAULT_REGION}"
    local_dir: build-kuberos
    upload-dir: kuberos
    on:
      branch: main
      